version: '3.8'

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=webui_external"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - webui_external
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_MODELS=${OLLAMA_MODELS:-/root/.ollama/models}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-5m}
      - OLLAMA_ORIGINS=${OLLAMA_ORIGINS:-}
      - OLLAMA_DEBUG=${OLLAMA_DEBUG:-false}
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-0}
      - OLLAMA_MAX_QUEUE=${OLLAMA_MAX_QUEUE:-512}
      - OLLAMA_LOAD_TIMEOUT=${OLLAMA_LOAD_TIMEOUT:-5m}
    networks:
      - ollama_internal
      - ollama_external

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui_data:/app/backend/data
    depends_on:
      - ollama
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webui_external"
      - "traefik.http.routers.open-webui.rule=Host(`open-webui.docker.localhost`)"
      - "traefik.http.routers.open-webui.entrypoints=web"
      - "traefik.http.services.open-webui.loadbalancer.server.port=8080"
      - "traefik.http.services.open-webui.loadbalancer.passhostheader=true"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_AUTH=${WEBUI_AUTH:-true}
      - WEBUI_NAME=${WEBUI_NAME:-Ollama WebUI}
      - WEBUI_URL=${WEBUI_URL:-http://open-webui.docker.localhost}
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY:-changeme}
    restart: unless-stopped
    networks:
      - ollama_internal
      - webui_external

networks:
  ollama_internal:
    driver: bridge
    internal: true
  ollama_external:
    driver: bridge
  webui_external:
    driver: bridge

volumes:
  ollama_data:
    name: ollama_data
  open-webui_data:
    name: open-webui_data 